version: '3'

env:
  UID: '{{.UID | default "$(id -u)"}}'
  GID: '{{.GID | default "$(id -g)"}}'
  STOP_HEIGHT: '{{.STOP_HEIGHT | default "1000"}}'
vars:
  IMAGE_NAME: peercoin-node
  CONTAINER_NAME: peercoin-node
  DATA_DIR: /home/peercoin/.peercoin

tasks:
  build:
    desc: Build the Docker image
    cmds:
      - docker build --build-arg UID="{{.UID}}" --build-arg GID="{{.GID}}" -t {{.IMAGE_NAME}} .
    sources:
      - Dockerfile
      - 0001-enforce-stopatheight-option.patch

  sync:
    desc: Sync the blockchain up to a specific height and stop
    deps: [build]
    cmds:
      - mkdir -p peercoin-data
      - |
        docker run --rm -v "$(pwd)/peercoin-data:{{.DATA_DIR}}" -u peercoin:peercoin --name {{.CONTAINER_NAME}} {{.IMAGE_NAME}} peercoind -printtoconsole -stopatheight="{{.STOP_HEIGHT}}" &
        DOCKER_PID=$!
        while ! docker exec {{.CONTAINER_NAME}} peercoin-cli getblockchaininfo >/dev/null 2>&1; do
          sleep 15
        done
        height=$(docker exec {{.CONTAINER_NAME}} peercoin-cli getblockcount)
        if [ "$height" -ge "{{.STOP_HEIGHT}}" ]; then
          docker exec {{.CONTAINER_NAME}} peercoin-cli stop
        fi
        wait $DOCKER_PID

  dump-utxos:
    desc: Restart the node with network disabled and dump UTXOs
    deps: [sync]
    cmds:
      - docker run --rm -d -v $(pwd)/peercoin-data:{{.DATA_DIR}} -u peercoin:peercoin --name {{.CONTAINER_NAME}} {{.IMAGE_NAME}} peercoind -networkactive=0
      - |
        until docker exec {{.CONTAINER_NAME}} peercoin-cli getblockchaininfo >/dev/null 2>&1; do
          sleep 1
        done
      - |
        current_height=$(docker exec {{.CONTAINER_NAME}} peercoin-cli getblockcount)
        if [ "$current_height" -ne "{{.STOP_HEIGHT}}" ]; then
          echo "Error: Current block height ($current_height) does not match STOP_HEIGHT ({{.STOP_HEIGHT}})"
          docker exec {{.CONTAINER_NAME}} peercoin-cli stop
          exit 1
        fi
      - docker exec {{.CONTAINER_NAME}} peercoin-cli dumptxoutset peercoin_utxos.dat
      - docker exec {{.CONTAINER_NAME}} peercoin-cli stop
      - mv peercoin-data/peercoin_utxos.dat .
